apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gaming
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: greatestworks-auth:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: development
            - name: SERVER_HTTP_HOST
              value: "0.0.0.0"
            - name: SERVER_HTTP_PORT
              value: "8080"
            - name: MONGODB_URI
              value: "mongodb://admin:admin123@mongodb:27017/admin"
            - name: MONGODB_DATABASE
              value: "auth_service"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              value: "redis123"
            - name: JWT_SECRET
              value: "dev-secret-change-me"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gaming
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
