apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: gaming
  labels:
    app: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: greatestworks-game:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: APP_ENV
              value: development
            - name: MONGODB_URI
              value: "mongodb://admin:admin123@mongodb:27017/admin"
            - name: MONGODB_DATABASE
              value: "mmo_game"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              value: "redis123"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: gaming
  labels:
    app: game-service
spec:
  type: ClusterIP
  selector:
    app: game-service
  ports:
    - name: rpc
      port: 8081
      targetPort: 8081
