app:
  name: "GreatestWorks Replication"
  version: "1.0.0"
  environment: "development"
  debug: false

service:
  name: "replication-service"
  version: "1.0.0"
  environment: "development"
  node_id: "replication-node-1"

server:
  http:
    host: "0.0.0.0"
    port: 8085
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  fields:
    service: "replication-service"
    version: "1.0.0"

monitoring:
  health:
    enabled: true
    path: "/health"
  metrics: # deprecated legacy settings
    enabled: false
    namespace: "replication_service"
  profiling:
    enabled: true
    host: "0.0.0.0"
    port: 6064
