app:
  name: "GreatestWorks Scene"
  version: "1.0.0"
  environment: "development"
  debug: false

service:
  name: "scene-service"
  version: "1.0.0"
  environment: "development"
  node_id: "scene-node-1"

server:
  http:
    host: "0.0.0.0"
    port: 8083
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  rpc:
    host: "0.0.0.0"
    port: 8084
    max_connections: 1000
    timeout: "30s"
    keep_alive: true
    keep_alive_period: "30s"
    read_timeout: "30s"
    write_timeout: "30s"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  fields:
    service: "scene-service"
    version: "1.0.0"

monitoring:
  health:
    enabled: true
    path: "/health"
  metrics: # deprecated legacy settings
    enabled: false
    namespace: "scene_service"
  profiling:
    enabled: true
    host: "0.0.0.0"
    port: 6063
